### ISSUE TITLE
Why is macros a separate project?

### ISSUE THREAD

**Issue by mpollmeier** [mpollmeier/gremlin-scala#100]
@joan38 what was the reason that you pulled out macros as a separate project? 
I'd like to introduce a type `Label` to gain some type safety (as supposed to use `String` everywhere). I've started it here: https://github.com/mpollmeier/gremlin-scala/compare/labelType

Problem: `Label` is defined in gremlin-scala, macro doesn't depend on it. 
Solution 1: pull out another 'shared' library
Solution 2: move macro code to gremlin-scala

I'd prefer Solution 2 as it's less complexity rather than more, if people try and understand what's happening. Thoughts?

**Comment by joan38** [comment]
Hi,

This is because you can't have macros applying to a code in the same compilation unit.
You need to compile the macros first and then you can use them.

**Comment by mpollmeier** [comment]
Ok that makes sense, thank you.
