### ISSUE TITLE
library method documentation?

### ISSUE THREAD

**Issue by zeryx** [mpollmeier/gremlin-scala#112]
Hey @mpollmeier I'm a big fan of the adapter but unfortunately I've been having some trouble determining exactly how to construct complex traversals and even relatively simple ones (find the vertex that has a max property value N). 

Am I missing something simple on where you store the libraries documentation or is it not released yet?

**Comment by mpollmeier** [comment]
moved to gitter: https://gitter.im/mpollmeier/gremlin-scala
