### ISSUE TITLE
Connecting to a remote gremlin server

### ISSUE THREAD

**Issue by phani1kumar** [mpollmeier/gremlin-scala#118]
Hi
Thank you for such a nice module for bringing in the beauty of Gremlin into the scala world. 

Would it be possible now to connect to a remote gremlin server? If it is not possible now, is it in the road map for near future? This is related to https://github.com/mpollmeier/gremlin-scala/issues/92

**Comment by mpollmeier** [comment]
i haven't looked into gremlin server yet, but put it on my list. just update this ticket if you figured something out yourself.

**Comment by mpollmeier** [comment]
a major problem will be to serialise custom traversals with things like `.filter(myLambda)`...
Maybe we can reuse something from spark? They serialise code and execute it remotely...

**Comment by phani1kumar** [comment]
thank you for your response @mpollmeier . I'll update if I am able to find anything relevant regarding this.

**Comment by tolbertam** [comment]
Since `gremlin-scala` operates on `GraphTraversalSource`, this should work with a few caveats that are limitations of using remote graph,  such as the use of lambdas as mentioned earlier and that Vertices/Edges returned from Traversals will be Detached.   I did an experimentation with hooking gremlin-scala up to a remote DataStax Enterprise Graph cluster and it worked well!

I set up a repository @ [tolbertam/gremlin-scala-dse-example](https://github.com/tolbertam/gremlin-scala-dse-example) that includes a very basic example showing that such a thing is possible.  So far I haven't bumped into any gremlin-scala specific issues but will report separate issues if I run into anything.

**Comment by mpollmeier** [comment]
@tolbertam thank you for setting that up. Would you mind if we copy or move that to https://github.com/mpollmeier/gremlin-scala-examples ? I could just add you as a collaborator.

**Comment by tolbertam** [comment]
@mpollmeier thanks, it was fun to set up and experiment with, `gremlin-scala` is super neat!  Will see about contributing to `gremlin-scala-examples`, will get back to you on that hopefully this coming week 👍

**Comment by tolbertam** [comment]
I realized after looking at gremlin-scala a bit that there is one small thing missing (either that or i'm just missing it myself) as it pertains to working with a remote graph.   Looking at the docs, one creates a `ScalaGraph` from a `Graph` instance, but by using [`withRemote`](http://tinkerpop.apache.org/docs/current/reference/#connecting-via-remotegraph) which the dse driver effectively does, the underlying `Graph` for the traversal source is an `EmptyGraph` instance.

So in effect, using `DseGraph.traversal(...).getGraph` yields an empty graph so getting a `ScalaGraph` from that doesn't do much good.  I can use the `GraphTraversalSource` itself and get some functionality out of gremlin-scala, but it looks like to get the type-safe methods (such as using `Key`) and so on, we'll need a way to create a `ScalaGraph` from a `GraphTraversalSource` directly, which looks rather easy, it's just a matter of adding the following to `package.scala`:

```scala
  implicit class GraphTraversalSourceAsScala(g: GraphTraversalSource) {
    def asScala() = ScalaGraph(TraversalSource(g))
  }
```

I'll open a PR for that (hopefully that makes sense, could be something I'm missing).

I also noticed that `ScalaGraph` lacks an `addV` and `inject` methods method, which are both valid ways to start a traversal so i'll open up a PR for adding those too if that makes sense.

**Comment by mpollmeier** [comment]
Correct, Gremlin-Scala just wraps the Java classes wherever we can add something. That GraphTraversalSourceAsScala makes sense. 

`ScalaGraph` does have `addV` (I just called it `addVertex`). Also note that we have a nicer syntax to add vertices/edges, you might want to use that instead (it's documented on the front page (readme))

`inject` is part of `GremlinScala` (which wraps the traversal) - looks like it does cover all use cases described in http://tinkerpop.apache.org/docs/current/reference/#inject-step , or is there something missing?

**Comment by mpollmeier** [comment]
I think it would make sense to add `withRemote` to https://github.com/mpollmeier/gremlin-scala/blob/master/gremlin-scala/src/main/scala/gremlin/scala/TraversalSource.scala . Just some random thoughts on how the API would look then:
```
val g = graph.asScala.withRemote(DriverRemoteConnection.using(cluster, "g"))
g.V.toList //executes remotely, sending gremlin binary over the wire
g.V.getBytecode
g.V.getBytecode.getBindings
// this is probably quite a thin wrapper, just calling the existing functions in gremlin-java
// graph is the standard tinkerpop Graph
graph.asScala // makes it a ScalaGraph (that's already the case)
graph.asScala.withRemote makes it a RemoteGraph (doesn't yet exist)
```

**Comment by tolbertam** [comment]
I like your idea better and it would be more symmetric to how the TinkerPop docs describe using remote graphs.

In the example you give above, `graph` is simply an `EmptyGraph` right?

The [`DseGraph`](http://docs.datastax.com/en/drivers/java-dse/1.2/com/datastax/dse/graph/api/DseGraph.html) class in the driver is more of a convenience mechanism to create a `GraphTraversalSource` from a `DseSession`, but ultimately it uses [`DseRemoteConnection`](http://docs.datastax.com/en/drivers/java-dse/1.2/com/datastax/dse/graph/internal/DseRemoteConnection.html) under the covers.  With your proposal, I think this would work:

```scala
val g = EmptyGraph.instance().asScala
  .configure(_.withRemote(DseRemoteConnection.builder(dseSession).build())
```

To make it work would it be as simple as adding the following to `TraversalSource`?:

```scala
  def withRemote(connection: RemoteConnection): TraversalSource =
    TraversalSource(underlying.withRemote(connection))
```

If so I really like that.  Probably would be good to also add the overloaded `withRemote` methods as well (that take in Configuration and String for configFile path)

**Comment by tolbertam** [comment]
I just realized I missed your prior comment, responses below:

> ScalaGraph does have addV (I just called it addVertex). Also note that we have a nicer syntax to add vertices/edges, you might want to use that instead (it's documented on the front page (readme))

I think the difference is that `addVertex` on a `Graph` instance does not create a traversal, it operates directly on the Graph where `addV` operates on the traversal source and creates a traversal.  Since remote connections can use an `EmptyGraph` as its initial basis `Graph.addVertex` will fail.

> inject is part of GremlinScala (which wraps the traversal) - looks like it does cover all use cases described in http://tinkerpop.apache.org/docs/current/reference/#inject-step , or is there something missing?

`inject` can be used directly on `GraphTraversalSource` to start a traversal, where with `gremlin-scala` it cannot from what I can tell, although i'm not sure how inherently useful it is to start a traversal from the `inject` step (just something I noticed)

**Comment by mpollmeier** [comment]
Yes, I guess it would be an `EmptyGraph` (I haven't used the DSE driver myself yet). 

And yes, that should be all that's needed. That's why I build the TraversalSource wrapper in the first place, to make this kind of stuff simple :)

I guess we can't really have a test for this code inside this repo, therefor it'd be great if you could set something up in the gremlin-scala-example companion repo that actually uses it. I'll grant you push access for both now.

**Comment by tolbertam** [comment]
Sounds good.  I have a work in progress for an example to go into gremlin-scala-examples, i'll open up a PR there soon.   It works similar to the neo4j-bolt one where you need a local instance running to run the test successfully (like neo4j-bolt it includes some documentation for how to run a docker container for testing).

> I guess we can't really have a test for this code inside this repo..

We could sort of validate it in a unit test following what tinkerpop did to test `withRemote` by using a mock `RemoteConnection`, albeit all that test does it ensure that when the graph closes, the remote connection is also closed: https://github.com/apache/tinkerpop/blob/9b13383449e23dd3a8e13d3c60736823f6e03ae5/gremlin-core/src/test/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversalSourceTest.java#L42-L48

I tried out the implementation using `TraversalSource#withRemote` and it did work.  I'll create a PR for that.

**Comment by mpollmeier** [comment]
Cool. 
Re unit test: not sure if that really adds much value. Up to you if you want to add it or not.

**Comment by mpollmeier** [comment]
thanks for your PRs, @tolbertam 
Let me know when you would like a new release, it's easy for me to do.

**Comment by tolbertam** [comment]
Thanks for reviewing and merging!  As far as a new release, I don't have an urgent need for it other than that the example i'm creating uses the changes, so it can be done whenever convenient for you 👍

**Comment by mpollmeier** [comment]
just released to enable https://github.com/mpollmeier/gremlin-scala-examples/pull/25
