### ISSUE TITLE
Consider providing version of `fold` with seed value and reduce function

### ISSUE THREAD

**Issue by metasim** [mpollmeier/gremlin-scala#127]
Basically expose capability shown in example (3).

http://tinkerpop.apache.org/docs/3.1.0-incubating/#fold-step

I could have a go at it if you accept pull requests.

**Comment by mpollmeier** [comment]
That would be great, thank you. The tests for this would probably best fit into the `TraversalSpec`. Let me know if you need help with anything!

**Comment by metasim** [comment]
@mpollmeier Getting started on it, and want to know if the Scala version should be called `fold` or `foldLeft`? So far with my simple tests its behaving like a `foldLeft`, but I didn't know if there was any guarantee of order on the TinkerPop side. Thoughts?

**Comment by metasim** [comment]
Proposed implementation: #128

**Comment by mpollmeier** [comment]
+1 for foldLeft

**Comment by metasim** [comment]
#128 merged so closing.
