### ISSUE TITLE
Add wrapper for `choose`

### ISSUE THREAD

**Issue by metasim** [mpollmeier/gremlin-scala#131]
(Docs: http://tinkerpop.apache.org/docs/3.1.0-incubating/#choose-step)

Is this just a "haven't gotten around to it" kind of feature (in that case I can have a go at it), or is there a particular challenge with the types. If the latter, will the upcoming `union` tweaks assist?

**Comment by mpollmeier** [comment]
i haven't gotten around to it and would be happy to see you contributing. the type challenge will indeed be similar to `union`, so it might make sense to hold off for a week

**Comment by metasim** [comment]
@mpollmeier I saw some commits around `union`... is it ready use as a template?

**Comment by mpollmeier** [comment]
`union` is as good as I can get it without changing the semantics between gremlin-scala and gremlin-groovy too much. So: yes, that's probably a good starting point. Let me know once you have a first version and I'll give you some feedback.
