### ISSUE TITLE
default case class marshalling fails depending on compilation order

### ISSUE THREAD

**Issue by yusefnapora** [mpollmeier/gremlin-scala#133]
Hi, I've been having a very odd problem trying to use the default `toCC` marshalling for case classes.

Here's the basic scenario.  In `Types.scala`:

```scala
package org.mypackage

import gremlin.scala._
import com.orientechnologies.orient.core.id.ORecordId

object Types {
  case class Foo(@id id: Option[ORecordId], bar: String)

  def findFoo(graph: Graph, bar: String): Option[Foo] 
    val Bar = Key[String]("bar")
    graph.V.has(Bar, bar).toCC[Foo].headOption
  }
}
```

That works fine... but, if I move `findFoo` to a different file named `Query.scala`:

```scala
package org.mypackage

import org.mypackage.Types._
object Query {
    def findFoo(graph: Graph, bar: String): Option[Foo] {
      val Bar = Key[String]("bar")
      graph.V.has(Bar, bar).toCC[Foo].headOption
    }
}
```

Then `findFoo` will return a `Foo` whose `id` is `None`, instead of `Some(ORecordId("v1:2"))`.

I've attached a debugger to `sbt` so I can set a breakpoint in the `Marshallable` macro implementation that will trip during `sbt compile`.  If I set my breakpoint here: https://github.com/mpollmeier/gremlin-scala/blob/3.1.1-incubating/macros/src/main/scala/gremlin/scala/Marshallable.scala#L99 so that it triggers when the macro sees the `@id` annotation, the breakpoint will trip when the `toCC` usage happens in `Types.scala`, but it won't trip if you move the usage of `toCC` to `Query.scala`.

However, if I modify `Query.scala` in any way (so sbt will recompile it), and recompile (without cleaning the earlier compilation), then the breakpoint _will_ trigger for the macro usage in `Query.scala`.  The second compilation pass is able to see the `@id` annotation, and everything works.

This seems to indicate that the compilation order matters here, but I'm not familiar enough with scala (and especially with the macro system) to know what my options are for fixing it...

**Comment by parkan** [comment]
Update: it appears that this is caused by sbt's alphabetical-first compile order. Renaming `Types.scala` to `AAATypes.scala` appears to resolve the issue

**Comment by joan38** [comment]
Could you try both cases with a full clean compile: `sbt clean compile`?

Cheers

**Comment by yusefnapora** [comment]
Sure.  switching from made up examples to our actual project...

We've got a spec that has this assertion: `person.id must beSome` where `person` is an instance of a case class with an `@id` annotated `id` field.

Using `sbt clean compile` followed by `sbt test`:

If our case classes are defined in `Types.scala`, the test fails, but renaming to `$Types.scala` (or `AAATypes.scala`, etc) causes it to pass.

**Comment by mpollmeier** [comment]
Unfortunately that sounds like a compiler or macro bug, and I'm not versed enough to figure out a fix for that. we've been thinking about using shapeless instead of the macro (in fact we used to use shapeless for serialisation in the past), so this is one more reason to go down that route. 

For now you'll either have to live with the ugly workaround of renaming your file, or not use the macro and instead write your own marshaller instance. Sorry.

**Comment by parkan** [comment]
Sounds like we should cross-post to https://groups.google.com/forum/#!forum/sbt-dev

**Comment by yusefnapora** [comment]
Right on, thanks @mpollmeier.  I'm going to close this, since it's not specific to gremlin-scala.  We're okay with the filename workaround for now :)
