### ISSUE TITLE
Expose `coalesce`.

### ISSUE THREAD

**Issue by metasim** [mpollmeier/gremlin-scala#137]
Ref: http://tinkerpop.apache.org/docs/3.1.1-incubating/reference/#coalesce-step

**Comment by mpollmeier** [comment]
to speed things up, maybe you could provide a PR? Implementing this shouldn't be hard, just add a test to `TraversalSpec.scala` and add the implementation to `GremlinScala.scala`

**Comment by metasim** [comment]
@mpollmeier @analytically asked me about this on my fork. Best I can tell this feature is merged. Do you concur, and think this can be closed?

**Comment by mpollmeier** [comment]
coalesce is merged and is part of 3.1.2-incubating.0
