### ISSUE TITLE
When will 3.1.1-incubating.3 be released?

### ISSUE THREAD

**Issue by szdavid92** [mpollmeier/gremlin-scala#150]
Hi @mpollmeier,
I really like your project, cool stuff! 
Do you have a timeline for releasing 3.1.1-incubating.3? 
I would like to use the `addV` and `addE` steps.

**Comment by mpollmeier** [comment]
I didn't have a timeline... so I released it just now, should be in maven central shortly :)

**Comment by szdavid92** [comment]
Thanks, I close this issue then.
