### ISSUE TITLE
Unable to use `until` with non-vertex traversals 

### ISSUE THREAD

**Issue by szdavid92** [mpollmeier/gremlin-scala#151]
```
val g = TinkerFactory.createModern().asScala
g.V(1).repeat(_.out()).until(_.outE().count().is(JLong.valueOf(0))).path().by("name").toList
```

produces
```
Error:(43, 50) type mismatch;
 found   : gremlin.scala.GremlinScala[Long,shapeless.HNil]
 required: gremlin.scala.GremlinScala[gremlin.scala.Vertex, _]
    (which expands to)  gremlin.scala.GremlinScala[org.apache.tinkerpop.gremlin.structure.Vertex, _]
g.V(1).repeat(_.out()).until(_.outE().count().is(JLong.valueOf(0))).path().by("name")
                                                ^
```

This query is from the Tinkerpop3 [documentation for `repeat`](https://tinkerpop.incubator.apache.org/docs/3.0.1-incubating/#repeat-step)

**Comment by szdavid92** [comment]
The same with `where`, as in [here](https://github.com/mpollmeier/gremlin-scala-examples/blob/master/tinkergraph/src/test/scala/MovieLensSpec.scala#L137) doesn't seem to work.
Am i missing something?

**Comment by mpollmeier** [comment]
you're absolutely right. fixed and added a test. releasing 3.1.1-incubating.4 now

**Comment by szdavid92** [comment]
It works, thanks!
