### ISSUE TITLE
Canonical way of updating a Vertex/Edge via case class

### ISSUE THREAD

**Issue by mikolak-net** [mpollmeier/gremlin-scala#156]
While there is an easy way to add vertices based on case classes (via `+[CC]`), a simple, "canonical"  method of persisting vertex changes via the same route seems to be absent - since `addVertex` is intended solely for addition.

A quick & dirty solution can be something like the following (pseudocode) :

```scala
val savedCc: CC = graph.+[CC](newCc)

val modifiedCc: CC = modify(savedCc) //where modify changes some fields
val m = implicitly[Marshallable[CC]]

for(
    vertex <- graph.V(savedCc.id.get).headOption;
    (k, v) <- m.fromCC(modifiedCc).valueMap
) {
   vertex.property(k, v)
}
```

However, this is hardly ideal.

Is there a better way to do perform a "case-classed" update in `gremlin-scala` (if so, it should probably be more documented)? If not, do you consider this kind of functionality worth adding to the API?

**Comment by mpollmeier** [comment]
Interesting point. No, there's currently no better way, but it might make sense to add it, e.g. as a separate method `graph.update(Id, CC)`, and the implementation would be similar to what you've provided there. 

The downside is obviously that we don't really know which fields were actually updated and have to update all of them, but in sake of simplicity that would be fine IMO. Thoughts? Would you like to draft a PR?

**Comment by mikolak-net** [comment]
Thanks for the reply. Regarding the downside, well, since we're already extracting the existing node, we might be tempted to e.g. compare on equality, but I don't really see the point of this, so I agree just changing everything would be fine.

I'll gladly cook up a PR (probably early next week). I'm still on the fence whether this should be a method of `ScalaGraph` or e.g. `ScalaVertex`, I'll play around and see how it works.

**Comment by mikolak-net** [comment]
I'm still somewhat unsatisfied with the solution I've provided. It's fine for scenarios where you are syncing your DB with some other data source (and hence already have a CC instance on hand), but it's clunky when you wish to simply _modify_ a vertex.

So, I'd like to additionally introduce something like this:
`def updateAs[CC](f: CC => CC): Vertex`
(the name could also be simply `update`)

One could argue that's it duplicates the functionality of `setProperty`, but transformation of case classes is so idiomatic in the Scala ecosystem I'd say a method like the above will add value.

What do you think?

**Comment by mikolak-net** [comment]
I'm still somewhat unsatisfied with the solution I've provided. It's fine for scenarios where you are syncing your DB with some other data source (and hence already have a CC instance on hand), but it's clunky when you wish to simply modify a vertex.

So, I'd like to additionally introduce something like this:
def updateAs[CC](f: CC => CC): Vertex
(the name could also be simply update)

One could argue that's it duplicates the functionality of `setProperty`, but transformation of case classes is so idiomatic in the Scala ecosystem I'd say a method like the above will add value.

@mpollmeier: what do you think?

**Comment by mpollmeier** [comment]
That's a great idea, I like it!

**Comment by mpollmeier** [comment]
I've just offered you collaborator access for this repo as well :)

**Comment by mikolak-net** [comment]
@mpollmeier : excellent, glad you like it!

Re collab - thanks, appreciate it very much :). Any guidelines on collaboration , or should I just commit to master/feature branches at own discretion?

**Comment by mikolak-net** [comment]
Also, I'll expand this issue to include edges as well, since otherwise there'd be divergent APIs for basically the same functionality.

**Comment by mpollmeier** [comment]
sounds great. 

Re collaboration: I should have clarified beforehand: please never commit to master directly, unless it's something trivial (e.g. 46f4711 was fine). Always push a feature branch and open a PR so others have a chance to look. All commits you added look fine, i.e. PR is approved retrospectively :)

**Comment by mikolak-net** [comment]
Arghh, got a little ahead of myself, haven't I? Sorry! Glad to hear present changes are OKd.
