### ISSUE TITLE
Support for 3.2.0?

### ISSUE THREAD

**Issue by analytically** [mpollmeier/gremlin-scala#160]
TinkerPop 3.2.0 (Release Date: April 8, 2016) support.

**Comment by mpollmeier** [comment]
thanks for the reminder, will do once I'm back from my travels (end of this week)

**Comment by analytically** [comment]
Thanks!

**Comment by metasim** [comment]
+1. would like access (at least through `traversal`) to the new `project` step.

**Comment by mpollmeier** [comment]
just released 3.2.0... enjoy :)
