### ISSUE TITLE
How to create node so it can be seen in Neo4J db UI

### ISSUE THREAD

**Issue by jiancoding** [mpollmeier/gremlin-scala#162]
Hi, 
I am new to gremlin, scala and neo4j db, and keep playing them in the past several days, by following   example code below:
val Location = "location"
    val Name = Key[String]("name")
val dbPath = "/Neo4j/example"
val graph = Neo4jGraph.open(dbPath).asScala
val auckland = graph +(Location, Name → "Auckland") //add vertex with properties
graph.close

By open db file in neo4j graphic UI(CE version 3.0.03), I can't see any node created.
Did I miss anything? How to create a node with properties and relationships i?
Sorry about my silly question!! I just need a hint.
Thanks

**Comment by mpollmeier** [comment]
what you're doing looks right. I don't know much about neo4j graphic ui, but does the vertex exist if you query it with gremlin? i.e. open the same graph in a separate execution and just run something like `graph.V.value(Location).toList`

**Comment by jiancoding** [comment]
Thanks for your reply and helped me to figure it out.
Have a good weekend!
