### ISSUE TITLE
Traversals reference vertices after deletion

### ISSUE THREAD

**Issue by SmedbergM** [mpollmeier/gremlin-scala#196]
In a multiprocessor environment, a traversal will sometimes reference vertices which another thread/processor has already deleted. This causes the entire traversal to fail in an unrecoverable fashion and throw an uncaught exception.

MWE [here](https://github.com/SmedbergM/neo4j-deletion-error). Gist of the output log of one run [here](https://gist.github.com/SmedbergM/d9aacd1d4987f63b06e2b4749f85905d).

To be entirely honest, I'm very doubtful that this is a `gremlin-scala` issue. It seems much more likely that the responsibility lies somewhere in the Java implementation (either in `org.neo4j.???` or one of the Apache/Tinkerpop impls). I'd welcome a PR from anyone to my MWE project which peels off the `gremlin-scala` layer while preserving the observed error.

**Comment by mpollmeier** [comment]
agreed, I doubt that it's a gremlin-scala issue :)

**Comment by SmedbergM** [comment]
Can close: [46ddfdd6](https://github.com/SmedbergM/neo4j-deletion-error/commit/46ddfdd6b8ebb802aee72b7f19107be425960ece) removes the dependency on gremlin-scala.

NB: In the course of this, I discovered that `Transaction` is not thread-safe (in fact it's implemented with Apache's `ThreadLocal` class. That wasn't the underlying cause of the bug, but it's still worth putting into the documentation somewhere I think.

**Comment by mpollmeier** [comment]
thank you, will factor that in.
