### ISSUE TITLE
problems with JanusGraph

### ISSUE THREAD

**Issue by schiebel** [mpollmeier/gremlin-scala#202]
Hi,

I do not know if JanusGraph (beneath TinkerPop) is expected to work or not. However, I've been having a problem where the vertices I create are not stored to disk. They appear to be created but when I reopen the DB, using gremlin from the JanusGraph distro, there are no vertices in the DB. I have created a simple test (attached). This is the behavior I get (the 'submission' arg just selects the attached simple test case):

    bash$ java -jar /Users/drs/develop/scala/xml/xml-ccache/target/scala-2.12/ccache-assembly-0.0.1-SNAPSHOT.jar submission
    09:17:14,402  INFO GraphDatabaseConfiguration:1381 - Set default timestamp provider MICRO
    09:17:14,456  INFO GraphDatabaseConfiguration:1553 - Generated unique-instance-id=ac10fa0127916-odysseus-local1
    09:17:14,497  INFO Backend:466 - Configuring index [search]
    09:17:14,521  INFO Backend:183 - Initiated backend operations thread pool of size 8
    09:17:14,620  INFO KCVSLog:744 - Loaded unidentified ReadMarker start time 2017-04-26T13:17:14.571Z into org.janusgraph.diskstorage.log.kcvs.KCVSLog$MessagePuller@135606db
    >>>>>> v[4320]
    bash$ janusgraph-0.1.0-hadoop2/bin/gremlin.sh 
    objc[27917]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java (0x1017e74c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1019684e0). One of the two will be used. Which one is undefined.

             \,,,/
             (o o)
    -----oOOo-(3)-oOOo-----
    plugin activated: janusgraph.imports
    plugin activated: tinkerpop.server
    plugin activated: tinkerpop.utilities
    SLF4J: Class path contains multiple SLF4J bindings.
    SLF4J: Found binding in [jar:file:/Users/drs/develop/scala/xml/xml-ccache/testing/janusgraph-0.1.0-hadoop2/lib/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: Found binding in [jar:file:/Users/drs/develop/scala/xml/xml-ccache/testing/janusgraph-0.1.0-hadoop2/lib/logback-classic-1.1.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
    SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
    log4j:WARN No appenders could be found for logger (org.apache.hadoop.util.Shell).
    log4j:WARN Please initialize the log4j system properly.
    log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
    plugin activated: tinkerpop.hadoop
    plugin activated: tinkerpop.spark
    plugin activated: tinkerpop.tinkergraph
    gremlin> graph = JanusGraphFactory.open('berkeleyje:test.db')
    ==>standardjanusgraph[berkeleyje:/Users/drs/develop/scala/xml/xml-ccache/testing/test.db]
    gremlin> graph.vertices()
    gremlin> 
    bash$ 

Thanks for any advice!

[ScalaGremlin.txt](https://github.com/mpollmeier/gremlin-scala/files/958497/ScalaGremlin.txt)

**Comment by tolbertam** [comment]
Hi @schiebel, I tried out your example, and I believe the reason that your vertex is not being persisted is because you are not committing a transaction.  If believe if you add `graph.tx().commit()` after you add the vertex, it should now be visible from your gremlin console, at least that seemed to work for me.

**Comment by schiebel** [comment]
Excellent! Indeed it does. Thank you very much for taking the time to help with my problem, @tolbertam
