### ISSUE TITLE
Async (promise()) traversal support

### ISSUE THREAD

**Issue by tolbertam** [mpollmeier/gremlin-scala#203]
[TINKERPOP-1490](https://github.com/apache/tinkerpop/pull/478) in 3.2.4 introduced the capability to execute traversals asynchronously, i.e.:

```java
CompletableFuture marko = g.V().hasLabel("person")
  .has("name","marko")
  .promise(Traversal::next);
```

It would be nice for gremlin-scala to support this and return scala futures which could make for some really neat stuff!

I'm still experimenting with this on the java side, but think this could be somewhat straightforward to implement.  I think one possible weakness is the current element type of the Traversal is lost when using `promise` (there's probably a way to overcome that in tinkerpop itself, looking into it).

**Comment by tolbertam** [comment]
> I think one possible weakness is the current element type of the Traversal is lost when using promise (there's probably a way to overcome that in tinkerpop itself, looking into it).

That will be fixed by [TINKERPOP-1670](https://issues.apache.org/jira/browse/TINKERPOP-1670).  Still experimenting with this feature on the java side, but was curious about what you thought as it pertains to supporting this in gremlin-scala.

**Comment by mpollmeier** [comment]
agreed, would be great to get that into gremlin-scala, and yes, that shouldn't be hard. Re the types: it would be good to get your PR https://github.com/apache/tinkerpop/pull/604 merged, but I don't think we need to wait for it (we might have to add a cast though). 

Would the step signature in GremlinScala look like this then? 
```
def promise[NewEnd](fun: GremlinScala[End, Labels] => NewEnd): Future[NewEnd]
```

**Comment by tolbertam** [comment]
That looks right to me!  You are right that this can be done via casting, I made a rough attempt which probably could use some refinement:

```scala
  def promise[NewEnd](fun: GremlinScala[End, Labels] => NewEnd): Future[NewEnd] = {
    val promise = Promise[NewEnd]
    val wrapperFun = (t: Traversal[_, _]) => fun(GremlinScala(t.asInstanceOf[GraphTraversal[_, End]]))
    this.traversal.promise(wrapperFun).whenComplete {
      case (result, null) => promise.complete(Success(result))
      case (_, t) => promise.failure(t)
    }
    promise.future
  }
```

Even with TINKERPOP-1670 i think casting is still needed from `Traversal` to `GraphTraversal` to satisfy the `GremlinScala` constructor.

To test it out I added the following to `TraversalStrategySpec withRemote should cause Graph to use RemoteConnection`:

```scala
val future = remoteGraph.V().promise(_.toList())
val vertices = Await.result(future, FiniteDuration(100, MILLISECONDS))
result shouldEqual data
```

Although I wonder why TinkerPop's `promise` couldn't work with all Traversals, i'll read through the jira ticket/pull request to see if I can understand why that limitation exists to satisfy my curiosity there :).

**Comment by mpollmeier** [comment]
Looks good, where's the PR? :)
Just a minor idea: should we rename `fun` to `onComplete`?

**Comment by tolbertam** [comment]
> Looks good, where's the PR? :)

hah :).  I'll get that up shortly, have it in my working environment still so will push that out in a little bit.

> Just a minor idea: should we rename fun to onComplete?

Good call.  Will do that.
