### ISSUE TITLE
find node and add new node and edge in Neo4j Bolt

### ISSUE THREAD

**Issue by andyzeli** [mpollmeier/gremlin-scala#218]
I am having  an issue with Neo4J Bolt not committing newly created edges

`val Ident = Key[String]("personId")`
`val ItemId = Key[String]("movieId")`
//
`val thisNewNode = graph + ("PersonId", Ident -> "pers12")`
//look for existing nodes in graph
`graph.V.hasLabel("Foo").has(ItemId, "A123").toList.head.asScala.addEdge("likes", thisItem)`
 **** OR****
`val existingNode = graph.V.hasLabel("Foo").has(ItemId, 'A123').head`
`thisNewNode --- "likes"--> existingNode`
*****
//test if gremlin found and added node
`val len = neo.scala.graph.V().hasLabel("StoreItem").toList().head.in().toList().length`
`println(len)` // prints 1 as expected
`graph.graph.tx.commit()`

But when this is run, and I look at the Neo4j browser, the `PersonId` node will have been added but not the "likes" edge between it and the found existing node

**Comment by mpollmeier** [comment]
This works fine with other dbs, so it's very likely a neo4j-bolt problem, which I'm not an expert on. Please open an issue there, unless you know that it's actually gremlin-scala related.

**Comment by andyzeli** [comment]
Thanks Michael. Thats what I figured, and thats kind of annoying. perhaps
its time to look at a different DB.

On Sun, Aug 20, 2017 at 2:31 PM, Michael Pollmeier <notifications@github.com
