### ISSUE TITLE
When using Set or List on Key - Giving an error

### ISSUE THREAD

**Issue by harjitdotsingh** [mpollmeier/gremlin-scala#227]
I have the following definition
`  val atomEnergy = Key[Set[String]]("atomEnergy")
 val perm = graph.addVertex("perm")
    perm.setProperty(atomEnergy,Set("1"))
`

I get an exception saying

```
 AcmTestSpec *** ABORTED ***
[info]   java.lang.IllegalArgumentException: Property value [Set(1)] is of type class scala.collection.immutable.Set$Set1 is not supported
[info]   at org.apache.tinkerpop.gremlin.structure.Property$Exceptions.dataTypeOfPropertyValueNotSupported(Property.java:163)
[info]   at org.apache.tinkerpop.gremlin.structure.Property$Exceptions.dataTypeOfPropertyValueNotSupported(Property.java:159)
[info]   at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.verifyAttribute(StandardJanusGraphTx.java:580)
[info]   at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.addProperty(StandardJanusGraphTx.java:732)
[info]   at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.addProperty(StandardJanusGraphTx.java:722)
[info]   at org.janusgraph.graphdb.vertices.AbstractVertex.property(AbstractVertex.java:148)
[info]   at org.janusgraph.core.JanusGraphVertex.property(JanusGraphVertex.java:72)
[info]   at org.janusgraph.core.JanusGraphVertex.property(JanusGraphVertex.java:33)
```

**Comment by mpollmeier** [comment]
without  a reproducable build it's hard to help, but note that you're using scala's `Set`, you probably have to use `java.util.Set` instead

**Comment by harjitdotsingh** [comment]
What I'm trying to do is add multiple property values to a vertex key. How can I do that ? Is there an example in the tests ?

**Comment by mpollmeier** [comment]
just added one for you: a271eff3416ba64d65cfb38e0a9d4f6eac240019
With tinkergraph, this works fine. The underlying problem you have though, is that JanusGraph doesn't accept scala's Set. 

So you have to use some type that JanusGraph accepts. As mentioned, I'm guessing that java.util.Set will do.
