### ISSUE TITLE
Gettting an  error while  using ValueMap

### ISSUE THREAD

**Issue by harjitdotsingh** [mpollmeier/gremlin-scala#228]

**Comment by mpollmeier** [comment]
what the compiler tells you here is that `valueMap` only works on `Element`, and since you're trying to run it on a `Tree`, this doesn't compile, because a tree is not an element: `org.apache.tinkerpop.gremlin.process.traversal.step.util.Tree[_] <:< gremlin.scala.Element.`

**Comment by mpollmeier** [comment]
n.b. only vertex and edge are elements
