### ISSUE TITLE
Executing Raw Queries

### ISSUE THREAD

**Issue by harjitdotsingh** [mpollmeier/gremlin-scala#230]
How can I execute Raw Queries like `g.V().out("connectTo")`

**Comment by mpollmeier** [comment]
i don't understand your question, can you be more specific?

**Comment by harjitdotsingh** [comment]
instead of using the Scala DSL. I want to send in RAW queries to the graph engine which is a String but is actually a gremlin query. For Example When you send in the Raw queries to JDBC Driver you send in as "Select * From table name". I want to know how we can do that . Hope that makes sense. Right

**Comment by mpollmeier** [comment]
I.e. you would like to send a gremlin-groovy query as a string?
The answer to that depends on the graphdb (refer to it's documentation) and isn't part of gremlin-scala.

**Comment by harjitdotsingh** [comment]
at the end of the day Gremin Scala is using something underneath it to make those calls. Don't those interface support passing a String. I will see if Tinker Pop Allows it or no.
