### ISSUE TITLE
Is it possible to pass the typesafe Key type as a String, instead of [A]

### ISSUE THREAD

**Issue by thetuxedo** [mpollmeier/gremlin-scala#231]
Assume the type information is defined at runtime, e.g.
name: String
age: Int
createdOn: Date

How can I get Key[A] where Type is from the string "String", "Int", "Date"?

thanks

**Comment by mpollmeier** [comment]
not sure I understand. Are you saying the type of your property is a tuple `(String, Int, Date)`?

**Comment by thetuxedo** [comment]
no, let me clarifiy, the Type of the vertex property will be defined in a schema file created by end-user using GUI editor, so I won't know in advance(compile time) whether the property is of String, Int, or other type. 

I only know I will get a schema file, with property name and property data type.
Now the problem is how can I get a typesafe Key[A], with data type information in string.

1. Is it possible: Key[classTypeFromString(property.datatype)]? 
2. or Key(name).datetype("String"|"Int"|.....) 
3. or a general version like java api, without using Generic?

**Comment by mpollmeier** [comment]
Being type safe means that you know the property type at compile time. So you have to use the common supertype, which in this case is probably `Any`.
