### ISSUE TITLE
Async write/update support

### ISSUE THREAD

**Issue by apatzer** [mpollmeier/gremlin-scala#234]
I see in #203 / #204 that async support for graph traversals has been added. What about async support for writes?

For example:
```
case class Person(firstName: String, lastName: String)
graph.V().head.updateAs[Person](_.copy(firstName = "Name Change!)).promise()
```

Otherwise, it seems that any write operation is a synchronous (i.e. thread blocking) operation. When your graph DB is remote, that's going to be 5-50ms of blocking...

Is that true? Is the underlying network call asynchronous or blocking?

**Comment by mpollmeier** [comment]
The underlying gremlin-java only allows for async ops in a traversal, so your best bet is probably to update the property in a traversal like this. The below is repl-friendly, just replace `toList` with `promise` for async. 

```
import gremlin.scala._
import org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerFactory

val g = TinkerFactory.createModern.asScala
val Name = Key[String]("name")

g.V(1).property(Name, "updated").toList
g.V.value(Name).toList //List(updated, vadas, lop, josh, ripple, peter)
```

> Is the underlying network call asynchronous or blocking?

That depends on the database driver implementation.

**Comment by apatzer** [comment]
Not sure sure I understand. Should it be:
```
g.V(1).promise(_.property(Name, "updated"))
```
to become async? `promise` takes an `onComplete` method.

**Comment by apatzer** [comment]
Is there any way to do this with case classes? Otherwise, one needs a `Key[_]` per case class property.

**Comment by mpollmeier** [comment]
`promise` takes an `onComplete` lambda, which you may or may not need. I guess there should be an overloaded `promise()` that doesn't take a lambda...

```
g.V(1).property(Name, "updated").promise(_ => _) // don't do anything with the result

// convert to case class
g.V(1).property(Name, "updated").promise(_.toCC[Person])
```

You may be confused by the fact that `g.V(1).property(Name, "updated")` is lazy - it doesn't do anything *unless* you execute the traversal with e.g. `toList` or `promise`. That's different to working with elements directly. Unfortunately you can't do much with case classes in the traversal, because you want to be able to execute your traversal remotely, and the DB typically doesn't know your case class.

**Comment by mpollmeier** [comment]
I just got curious and actually pasted the above in my repl, and it doesn't compile.. hang in there

**Comment by mpollmeier** [comment]
ok, updated the above to something that compiles. Note that this only works with a remoteGraph and I haven't actually tested to run it against one yet.

**Comment by mpollmeier** [comment]
FYI: just added a little convenience step `promise()` in 35c21f8999b8cd127a07f0a8821d3b7c6553cb8d

**Comment by apatzer** [comment]
Thanks for the syntactic sugar!

It's clear now how to make async updates to Vertices and Edges. Is there any way to create Vertices and Edges asynchronously? E.g.
```
scala> val futV = graph.addVertexAsync()
futV: Future[scala.Vertex]
```

I'd like to get to the point where I can use `gremlin-scala` like Slick or another asynchronous DB. Each DB operation would (ideally) explicitly be a `Future` where the package allows configuration of it's own execution threadpool / actors.

**Comment by mpollmeier** [comment]
you can use the `addV` and `addE` steps to add vertices and edges during a traversal. Examples here:
https://github.com/mpollmeier/gremlin-scala/blob/master/gremlin-scala/src/test/scala/gremlin/scala/TraversalSpec.scala#L705
https://github.com/mpollmeier/gremlin-scala/blob/master/gremlin-scala/src/test/scala/gremlin/scala/TraversalSpec.scala#L769
