### ISSUE TITLE
ScalaVertex setProperties do no accept as parameter a Marshable CC

### ISSUE THREAD

**Issue by devsprint** [mpollmeier/gremlin-scala#243]
[ScalaVertex](https://github.com/mpollmeier/gremlin-scala/blob/master/gremlin-scala/src/main/scala/gremlin/scala/ScalaVertex.scala) setProperties do no accept as parameter a Marshable CC, similar with [ScalaEdge](https://github.com/mpollmeier/gremlin-scala/blob/master/gremlin-scala/src/main/scala/gremlin/scala/ScalaEdge.scala). Is there any reason for this or is it just a matter of providing an implementation for it ?

In my specific case I can use updateWith instead.

**Comment by mpollmeier** [comment]
The latter. In hindsight I guess `updateWith` is misnamed - maybe we should deprecate it and provide the implementation under the name `setProperties`. Thoughts?

**Comment by devsprint** [comment]
@mpollmeier Based on current implementation I think we should keep updateWith, as it is doing more than just setting some properties and in my opinion is very useful. A new `setProperties` method could be easier added. I can provide a pull request this evening.

**Comment by mpollmeier** [comment]
closed via https://github.com/mpollmeier/gremlin-scala/pull/244
