### ISSUE TITLE
Bump gremlin-scala lib version to 3.4.0.x after TinkerPop version bump to 3.4.0.

### ISSUE THREAD

**Issue by jeremysears** [mpollmeier/gremlin-scala#275]
After the TinkerPop version 3.4.0 merge, this library is still released as version 3.3.5.x.  Some magic needs to be done w/ the sbt-ci-release-early plugin to get releases to be tagged correctly.

**Comment by mpollmeier** [comment]
argh, I tagged it locally but didn't push it. should be fixed now

**Comment by izcet** [comment]
😅the latest release is still 3.3.5.2

**Comment by mpollmeier** [comment]
numbers...are...complicated. let's try this again, just one (four?) more time

**Comment by mpollmeier** [comment]
3.4.0.1 will shortly be on mvn central - it's on sonatype now:
https://oss.sonatype.org/content/repositories/public/com/michaelpollmeier/gremlin-scala_2.12/3.4.0.1/

**Comment by surveprasad** [comment]
Hey,
Is there a release for scala_2.11 instead of scala_2.12 compatible with tinkerpop-3.4?
Or can you release it?
I am trying to use it on spark based project which is still on scala_2.11 version.

**Comment by mpollmeier** [comment]
https://github.com/mpollmeier/gremlin-scala/commit/49514c8caf25ffc15a06dd62a9729ba8375aa430 fixes the 2.11 build. There you go: 
https://oss.sonatype.org/content/repositories/public/com/michaelpollmeier/gremlin-scala_2.11/3.4.0.2/

will be on maven central shortly
