### ISSUE TITLE
Getting Side Effects Of Traversal

### ISSUE THREAD

**Issue by fppt** [mpollmeier/gremlin-scala#280]
Hi

I am trying to figure out how to profile my traversals as well as get their result. According to the [tinkerpop docs](http://tinkerpop.apache.org/docs/current/reference/#profile-step) I should be able to do the following:

```
t = graph.traversal().V().profile('metrics')
t.iterate()
t.getSideEffects('metrics')
```

With the scala library I can create the traversal with the side effect of profiling:

```
val traversal = graph.traversal().V()
val resultWithMetrics = traversal.profile("metrics")
```

and I can get the results with:

```
val result = resultWithMetrics.toList()
```

But I can't figure our how to get the profile after that. Any help would be appreciated.

Thanks,

**Comment by fppt** [comment]
Figured it out. Just have to use the "raw" java:

```
resultWithMetrics.traversal.asAdmin.getSideEffects.get("metrics")
```

Will close this issue if no one else replies with a better approach.

**Comment by mpollmeier** [comment]
I guess it would make sense to expose them directly in gremlin-scala, as you suggested `GremlinScala.getSideEffects(name: String)`. Let's keep this open until that's done. Let me know if you want to send a PR, otherwise I'll take care of it.

**Comment by fppt** [comment]
I made an attempt at writing the wrapper to expose this. PR is linked above.

**Comment by mpollmeier** [comment]
merged, thank you!
