### ISSUE TITLE
Scala 2.13 support

### ISSUE THREAD

**Issue by To-om** [mpollmeier/gremlin-scala#285]
Hi,
Do you plan to crossbuild gremlin-scala for scala 2.13 ?

**Comment by mpollmeier** [comment]
yeah, just didn't get to it yet, life is too busy. 

just tried simply upgrading a few deps - `compile` works, `Test/compile` needs some love. 
:crossed_fingers: we don't need to touch the macros

**Comment by To-om** [comment]
[Scalamock](https://github.com/paulbutcher/ScalaMock/releases/tag/v4.3.0) has been released for 2.13. With this version, all gremlin-scala tests pass.

I don't know why but I had to add `override def getSteps: util.List[Step[_, _]] = super.getSteps` in TraversalStrategySpec > RemoteGraphFixture > new AbstractRemoteTraversal to make it work.

**Comment by mpollmeier** [comment]
Thanks for letting me know! And very strange indeed with the `getSteps` 'override'. 
will merge on green: https://github.com/mpollmeier/gremlin-scala/pull/286

**Comment by mpollmeier** [comment]
3.4.1.6 is released for scala 2.11, 2.12 and 2.13 :tada:
