### ISSUE TITLE
Update gremlin-scala to TinkerPop 3.5.x

### ISSUE THREAD

**Issue by DuncanHills** [mpollmeier/gremlin-scala#304]
JanusGraph 6.x uses TinkerPop 3.5.x. I'd like to do this work myself, actually. I'm opening this issue to track the work and get input as to how you have handled these upgrades in the past. Thanks.

**Comment by mpollmeier** [comment]
Thank you, I'm here to help if you need me :)

**Comment by lionelfleury** [comment]
#306
