### ISSUE TITLE
How can I use the snapshot project within my own project?

### ISSUE THREAD

**Issue by PhilAndrew** [mpollmeier/gremlin-scala#40]
So, this is more of a question than a bug/issue. How can I use this gremlin-scala snapshot in my own project? I tried to use it was follows.

I built this so that it would place the snapshot into the .m2 directory on my computer:
https://github.com/tinkerpop/tinkerpop3

Then in my sbt project:
lazy val tinkerPop3 = RootProject(uri("git://github.com/mpollmeier/gremlin-scala.git#%s".format("tinkerpop3-snapshot")))

Which I then add a a dependsOn
.dependsOn(tinkerPop3)

Then I go to compile my program and I get lots of errors about SFunction and SPredicate. Any suggestion? Thanks!

[info] Compiling 4 Scala sources to /home/home/.sbt/0.13/staging/cf2b138b3216f8c286ba/gremlin-scala/target/scala-2.11/classes...
[error] /home/home/.sbt/0.13/staging/cf2b138b3216f8c286ba/gremlin-scala/src/main/scala/com/tinkerpop/gremlin/package.scala:7: object SFunction is not a member of package com.tinkerpop.gremlin.util.function
[error] import com.tinkerpop.gremlin.util.function.SFunction
[error]        ^
[error] /home/home/.sbt/0.13/staging/cf2b138b3216f8c286ba/gremlin-scala/src/main/scala/com/tinkerpop/gremlin/package.scala:8: object SPredicate is not a member of package com.tinkerpop.gremlin.util.function
[error] import com.tinkerpop.gremlin.util.function.SPredicate
[error]

**Comment by metasim** [comment]
@mpollmeier Shall we close this?
