### ISSUE TITLE
Removing Edges

### ISSUE THREAD

**Issue by max-leuthaeuser** [mpollmeier/gremlin-scala#59]
Is there a way to remove Edges once they are added? A cant see any function for this in ```GremlinScala ```.

**Comment by mpollmeier** [comment]
True, this is missing in GS. However you always have access to the underlying `Edge`, i.e. if you have a `scalaEdge: ScalaEdge`, you can just do: `scalaEdge.edge.remove`.

**Comment by max-leuthaeuser** [comment]
That should work, thanks.
