### ISSUE TITLE
Indexing for the edges

### ISSUE THREAD

**Issue by omidb** [mpollmeier/gremlin-scala#60]
Hi,

I know how to do indexing on the vertices, is there any solution for doing it for the edges?

--Omid

**Comment by mpollmeier** [comment]
As mentioned before (https://github.com/mpollmeier/gremlin-scala/issues/50):
GremlinScala only provides a wrapping layer where it makes sense. In this case it looks like you're just using the main tinkerpop Graph interface, so Gremlin-Scala isn't involved.

**Comment by omidb** [comment]
yes, I know that gremlin scala is not involved, I just ask it as a general question.

**Comment by mpollmeier** [comment]
Sorry, I dont know and guess that it's graph db specific
