### ISSUE TITLE
`hasNot(key, value)` missing

### ISSUE THREAD

**Issue by petrjanda** [mpollmeier/gremlin-scala#69]
According to Gremlin docs there is a handy traversal `hasNot(key, value)` on both edges and vertices (http://gremlindocs.com/#filter/hasnot). I saw it was missing in `scala-gremlin`. Do I assume correctly its due to the fact that `GraphTraversal` doesn't expose it either? (https://github.com/apache/incubator-tinkerpop/blob/master/gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.java).

It would be awesome to have that one.

**Comment by petrjanda** [comment]
I don't have a Java background but do I understand that method like this:

```java
    public default GraphTraversal<S, E> hasNot(final String key, final Object value) {
        return this.not(__.has(key, value));
    }
```

would allow `scala-gremlin` to expose this either? Or perhaps is there any workaround which can be done from the `scala-gremlin` itself?

I've managed to do something like:

```scala
graph.V.filter { _
  .out("did").dedup()
  .has("name", event)
  .count.next() == 0
}
```

but

```scala
graph.V.hasNot("name", event)
```

would be much nicer.

**Comment by mpollmeier** [comment]
There's always a chance that some step is missing, and I agree that this would be a nice one. You're right: the reason it's not there is that it's not in GraphTraversal.java. And yes, we could implement this step in GremlinScala with something like: 
`where(P.not(__.has(key, value)))`
I'll give it a try later. 

Thanks for this suggestion Petr!

FYI gremlindocs.com is currently for version 2.x. You're looking at version 3, and the latest docs are here: http://www.tinkerpop.com/docs/3.0.0-SNAPSHOT/

**Comment by petrjanda** [comment]
Ah nice! Thanks @mpollmeier
