### ISSUE TITLE
case classes for Edges

### ISSUE THREAD

**Issue by omidb** [mpollmeier/gremlin-scala#79]
Is there any limit to put the same case classes on Edges? like:

```scala
case class Address(street:String,zip:Int)
val jefferson = Address("jefferson",11111)
from.addEdge(label = "road", to, jefferson)
```
to ask a better question, can we store all Map[String,Any] on all DBs ? if yes, then we can simply add this functionality.

**Comment by joan38** [comment]
Yes this is a work I was currently doing.

**Comment by omidb** [comment]
is there any difference between Edge and Vertex types?

**Comment by joan38** [comment]
In terms of the persisted key -> value, no there is no difference.

We can now close this issue as this feature in now fully supported.
