### ISSUE TITLE
sbt console broken

### ISSUE THREAD

**Issue by mpollmeier** [mpollmeier/gremlin-scala#86]
@joan38 since you split up the single build into two subprojects (git bisect told me it's 4f630250b0f68027e1), sbt console doesn't work anymore. I tried both `sbt console` in the root project and in the `gremlin-scala` subproject. It uses Scala 2.10 and doesn't know any of the sources:
```
scala> import gremlin.scala._
<console>:10: error: not found: value gremlin
       import gremlin.scala._
```
Do you know what's wrong there?

**Comment by joan38** [comment]
I think this is our issue:
http://stackoverflow.com/questions/24299043/why-does-sbt-console-not-see-packages-from-subproject-in-multi-module-project

**Comment by dkrieg** [comment]
If you type ```project gremlinScala``` you will be able to launch console but may not be able to see the macros project. I know, short term fix but good to know about if the need is urgent.

**Comment by joan38** [comment]
`sbt gremlinScala/console` is the way to go.

**Comment by mpollmeier** [comment]
ouch, I see. I tried gremlin-scala/console and that didn't work. In 2e9c67e I changed the subproject name to gremlin-scala, so now it's as you would expect: `sbt gremlin-scala/console`. Ok with you?

**Comment by joan38** [comment]
That's better indeed.
